### ISSUE TITLE
Internal server error when running site with MAMP in CGI Mode (Individual PHP version for every host)

### ISSUE THREAD

**Issue by philmmoore** [Rareloop/lumberjack#11]
I'm sure I won't be the only one running trying to run Lumberjack with MAMP but after installing and activating the theme the only thing I could access was the wordpress backend, trying to access the site thew an internal server error, here's the error apache threw:

`
FastCGI: comm with server "/Applications/MAMP/fcgi-bin/php7.1.12.fcgi" aborted: error parsing headers: duplicate header 'content-type', referer: http://lumberjack/wp/wp-admin/
`

Turning CGI mode off (Identical PHP version for all hosts) resolved the issue.

**Comment by adamtomat** [comment]
Thanks @philmmoore, I'll chat with @joelambert and see if there's anything we can do.

**Comment by joelambert** [comment]
@philmmoore we've been able to replicate and have identified the issue. Working on a patch now. Thanks for reporting this.

**Comment by joelambert** [comment]
@philmmoore we've got a fix on a branch which resolves the issue locally on MAMP PRO, are you able to test it for us?

You can checkout the branch by updating your `composer.json` to use the following:

```
"rareloop/lumberjack-core": "dev-bf-duplicate-headers@dev"
```

**Comment by craig-lovelock** [comment]
@joelambert 

I had the same issue, can confirm updating to suggested branch fixed the issue 👍🏻

**Comment by joelambert** [comment]
Thanks @craig-lovelock, this has now been merged into master as part of the `v3.2.1` release.
