### ISSUE TITLE
Wrong class on the WordPress Controllers documentation?

### ISSUE THREAD

**Issue by lmartins** [Rareloop/lumberjack#13]
What are the steps to reproduce this issue?
-------------------------------------------
Sorry, I would submit this as a PR whoever I'm not being able to get to docs in git, maybe its a Gitbook thing.

In the WordPress Controllers documentation, the TimberResponse class is being called with:
`use App\Http\Responses\TimberResponse;`

In my environment at least that doesn't work, and it needs to be:
`use Rareloop\Lumberjack\Http\Responses\TimberResponse;`

Thanks!

**Comment by adamtomat** [comment]
Ah yes that's an error on my behalf, good spot. Will get this patched when I get a chance (early next week). If you fancied doing a PR we you can do so on this repo:

https://github.com/Rareloop/lumberjack-docs

**Comment by adamtomat** [comment]
Fixed the documentation.
