### ISSUE TITLE
Enqueue Assets

### ISSUE THREAD

**Issue by lmartins** [Rareloop/lumberjack#17]
Hi, finally got the time to start experimenting with the new Lumberjack version and right away I'm getting a little confused about something really simple.

My apologies if this is not the best channel to ask this question, but how do you approach triggering methods that need to happen at specific moments of WordPress lifecycle, like enqueuing assets for example?

I've done it by adding a new `assets.php` file where I then setup the regular WP hooks, but I'm getting the feeling this is not the proper way to do it with Lumberjack, could you clarify please?

**Comment by adamtomat** [comment]
Thanks for the question! You're welcome to throw questions on our Slack group too if you wanted somewhere a little less formal:

http://slack.lumberjack.rareloop.com

To answer your question, the new Lumberjack is generally less opinionated about this sort of thing. You have a couple options:

- pop it in `functions.php`
- register your own service provider

Here's the docs for them:
https://docs.lumberjack.rareloop.com/container/service-providers

And here's what an example provider looks like.
https://github.com/Rareloop/lumberjack-core/blob/master/src/Providers/ThemeSupportServiceProvider.php

We feel like this gives the best flexibility for people. Happy to chat more if you want any more info.

**Comment by lmartins** [comment]
Thank you for the explanation Adam, I'll explore your suggestions and I've joined Slack too.

Thank you!
