### ISSUE TITLE
lumberjack-bedrock permission error while cloning Bedrock repository 

### ISSUE THREAD

**Issue by clams4shoes** [Rareloop/lumberjack#20]
What are the steps to reproduce this issue?
-------------------------------------------
1. `composer global require rareloop/lumberjack-bedrock-installer`
2. `lumberjack-bedrock -v new mysite`

What happens?
-------------
Permission error. lumberjack-bedrock is unable to clone Bedrock repository.

What were you expecting to happen?
----------------------------------
For lumberjack-bedrock to create a new Lumberjack site.

Any logs, error output, etc?
----------------------------
```
Checking out Bedrock
Install failed
Symfony\Component\Process\Exception\ProcessFailedException: The command "git clone --depth=1 'git@github.com:roots/bedrock.git' '/Users/andrew/devilbox/data/www/dev/htdocs/rosefarms/dev/rosefamily' && rm -rf '/Users/andrew/devilbox/data/www/dev/htdocs/rosefarms/dev/rosefamily/.git'" failed.

Exit Code: 128(Invalid exit argument)

Working directory: /Users/andrew/devilbox/data/www/dev/htdocs/rosefarms/dev

Error Output:
================
Cloning into '/Users/andrew/devilbox/data/www/dev/htdocs/rosefarms/dev/rosefamily'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

What versions of software are you using?
----------------------------------------
**Operating System:** macOS High Sierra 10.13.6

**PHP Version:** PHP 7.1.16

**Comment by adamtomat** [comment]
Thanks for the detailed info. Sometimes you get that error message if you don't have an SSH key added to your Github account. Are you able to rule this out for us please?

https://help.github.com/en/enterprise/2.15/user/articles/adding-a-new-ssh-key-to-your-github-account

**Comment by clams4shoes** [comment]
Hmm. I did have an SSH key added to my account, but it seems like there was an issue with it. After readding the key the issue seems to be resolved. ¯\_(ツ)_/¯

Thanks @adamtomat :)

**Comment by adamtomat** [comment]
Awesome to hear you got it resolved @clams4shoes 👍
